version: '2'
 
services:
  mysql:
    image: mysql
    container_name: mysql1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: simple
      MYSQL_DATABASE: counterdb 
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
  counter-manager:
     build:
       dockerfile: Dockerfile
       context: ./counter-manager
     ports:
       - 8090:8090     